techpack: wcd934x.c: remove unused variable
An unused variable will be exposed by a backport of mainline commit
0a5f41767444 ("kbuild: clang: disable unused variable warnings only
when constant").

../techpack/audio/asoc/codecs/wcd934x/wcd934x.c:10178:13: error: unused variable 'val' [-Werror,-Wunused-variable]

        int input, val;

                   ^

1 error generated.

(cherry picked from commit 8c146bfa485c3b5f5485cb07f01ebf37d07ceb30)
(cherry picked from commit 3adfea3c81d1e77dd2528a7eb529e0815e4d1b58)
(cherry picked from commit db9e50f5df6655d95e6c1bb439c6ab8a5c34b6ad)